apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: helloworldds
spec: 
  selector: 
    matchLabels: 
      app: helloworld
  template: 
    metadata: 
      name: helloworldpod
      labels: 
        app: helloworld
    spec: 
      containers: 
      - image: vamsireddy179/hello-world:latest
        name: helloworldcontainer
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
